before_install:
 - sudo apt-get update
 - sudo apt-get install -qq unixodbc unixodbc-dev
 - sudo apt-get install -qq libsqliteodbc
env:
 global:
   - DBI_DSN=dbi:ODBC:DRIVER=SQLite3
 matrix:
   - DBD_ODBC_UNICODE=1
   - 
language: perl
perl:
  - "5.30"
  - "5.28"
  - "5.26"
  - "5.24"
  - "5.22"
notifications:
  email:
    recipents:
      - mjevans@cpan.org
    on_success: always
    on_failure: always
  irc:
    channels:
      - "irc.perl.org#dbi"
    on_success: change
    on_failure: always
